Symbol fix
disorderedmaterials/plot pull request #66
Opened 2023-07-04 14:33 UTC by Pranavya-Vivek

=> "Symbol-Fix" adds Symbols to existing plots in the Error binary file.

=> In its output, users should be able to;
     - choose whether or not to display the symbols
     - choose the style of the symbols
     - choose the size of the symbols

2023-07-10 14:51 UTC, trisyoungs requested changes
A few small corrections, mostly naming, but looking good!

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow.h
> +    Mildred::StyleFactory1D::SymbolStyle shapestyle_{Mildred::StyleFactory1D::SymbolStyle::Triangle};
For consistency this variable should be in lowerCamelCase:
```suggestion
    Mildred::StyleFactory1D::SymbolStyle shapeStyle_{Mildred::StyleFactory1D::SymbolStyle::Triangle};
```

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow.ui
> +          <string>Error Bars</string>
Good spot!

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow_funcs.cpp
> +    ui_.StyleCombo->addItem(QString("Triangle"));
Shouldn't this be added to your new symbol-specific `QComboBox`?

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow_funcs.cpp
> +    connect(ui_.TriangleWidth, SIGNAL(valueChanged(double)), this, SLOT(setSymbolSize(double)));
The size parameter for our symbols needs to be general, so the `ui_.TriangleWidth` spinbox would be better renamed to:
```suggestion
    connect(ui_.SymbolSizeSpin, SIGNAL(valueChanged(double)), this, SLOT(setSymbolSize(double)));
```

2023-07-10 14:51 UTC, trisyoungs commented on src/renderers/1d/stylefactory.h
> +
I guess this is left over from our discussion on having a set of predefined anchor points? We should remove it for now since it isn't used, and besides I don't think an `enum`eration is the way to achieve it in a nice way.

2023-07-10 14:51 UTC, trisyoungs commented on src/renderers/1d/symbol_triangle.cpp
> +    double w = symbolMetric_/2.0;
It's a good habit to use `auto` when doing assignments and the type of the result is deducible from the right-hand side:
```suggestion
    auto w = symbolMetric_/2.0;
```

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow_funcs.cpp
> +    dataEntity_->setSymbolStyle(checked ? shapestyle_ : Mildred::StyleFactory1D::SymbolStyle::None);
```suggestion
    dataEntity_->setSymbolStyle(checked ? shapeStyle_ : Mildred::StyleFactory1D::SymbolStyle::None);
```

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow_funcs.cpp
> +        dataEntity_->setSymbolStyle(shapestyle_);
```suggestion
        dataEntity_->setSymbolStyle(shapeStyle_);
```

2023-07-10 14:51 UTC, trisyoungs commented on examples/errors/mainwindow_funcs.cpp
> +shapestyle_ = shapeindex == 0 ? Mildred::StyleFactory1D::SymbolStyle::Triangle : Mildred::StyleFactory1D::SymbolStyle::None;
```suggestion
shapeStyle_ = shapeindex == 0 ? Mildred::StyleFactory1D::SymbolStyle::Triangle : Mildred::StyleFactory1D::SymbolStyle::None;
```

2023-07-14 11:05 UTC, Pranavya-Vivek reviewed
The requested changes have been implemented and run perfectly on the Example Output!

2023-07-17 08:13 UTC, trisyoungs approved these changes
Looks good to me!  Still have some formatting issues in the code, so the CI isn't passing right now.  If we can get those fixed, this is ready to merge in.
:+1:

2023-07-17 15:44 UTC, merged